version: '3.7'
services:
  mysql:
    container_name: app_mysql
    image: mysql/mysql-server:8.0.20
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=kumparan_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./src/docs/sql:/docker-entrypoint-initdb.d

  redis:
    container_name: app_redis
    image: redis:latest
    ports:
      - 6379:6379